
# =============================================================================
# OPTIMAL SWITCHING RULES FOR DYNAMIC PHASOR METHOD SELECTION
# Generated by RL optimization on 2026-02-03 20:50
# =============================================================================

def should_use_instantaneous(time, di_dt, dv_dt, d2i_dt2, envelope_variation):
    """
    Determine whether to use Instantaneous Dynamic Phasor or Generalized Averaging.

    Parameters:
        time: Current simulation time [s]
        di_dt: Current derivative |di/dt| [A/s]
        dv_dt: Voltage derivative |dv/dt| [V/s]
        d2i_dt2: Current second derivative |d²i/dt²| [A/s²]
        envelope_variation: Relative envelope variation (0-1)

    Returns:
        True: Use Instantaneous Dynamic Phasor
        False: Use Generalized Averaging
    """
    # Optimal thresholds (RL-optimized)
    TIME_THRESHOLD = 1.000000e+00  # [s]
    DI_DT_THRESHOLD = 0.000000e+00  # [A/s]
    DV_DT_THRESHOLD = 0.000000e+00  # [V/s]
    D2I_DT2_THRESHOLD = 0.000000e+00  # [A/s²]
    ENVELOPE_THRESHOLD = 0.000000  # ratio

    # Use INSTANTANEOUS if ANY condition is met
    use_instantaneous = (
        time < TIME_THRESHOLD or
        abs(di_dt) > DI_DT_THRESHOLD or
        abs(dv_dt) > DV_DT_THRESHOLD or
        abs(d2i_dt2) > D2I_DT2_THRESHOLD or
        envelope_variation > ENVELOPE_THRESHOLD
    )

    return use_instantaneous


# Example usage:
# method = "instantaneous" if should_use_instantaneous(t, di_dt, dv_dt, d2i_dt2, env_var) else "averaging"
